# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2021-present Kaleidos INC

FROM taigaio/taiga-back:latest

COPY taiga/locale /taiga-back/taiga/locale
COPY taiga/users/templates/emails /taiga-back/taiga/users/templates/emails
COPY taiga/projects/templates/emails /taiga-back/taiga/projects/templates/emails
COPY taiga/projects/contact/templates/emails /taiga-back/taiga/projects/contact/templates/emails
COPY taiga/base/templates/emails /taiga-back/taiga/base/templates/emails
COPY taiga/feedback/templates/emails /taiga-back/taiga/feedback/templates/emails
COPY taiga/export_import/templates/emails /taiga-back/taiga/export_import/templates/emails
COPY settings/common.py /taiga-back/settings/common.py
